site_name: Практический курс Docs as Code

theme:
  name: material
  language: ru
  palette:
# Настройки для светлой темы
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Переключить на тёмную тему

    # Настройки для тёмной темы
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему

  features:
    - content.code.copy # Включает кнопку копирования кода во всех блоках
   # - toc.follow        # Подсвечивает и прокручивает активный раздел при скролле страницы
   # - navigation.tracking # Синхронизация хэша (#anchor) в адресной строке

nav:
  - Введение: index.md
  - Подготовка к курсу: prerequisites.md
  - Шпаргалки: cheatsheet.md
#  - Модуль 1: module-1.md
#  - Модуль 2: module-2.md
#  - Модуль 3: module-3.md
#  - Модуль 4: module-4.md
#  - Чек-лист по итогам: takeaway.md

markdown_extensions:
  - admonition                  # Блоки внимания (выноски)
  - pymdownx.details            # Сворачиваемые блоки
  - pymdownx.superfences        # Улучшенные блоки кода
  - pymdownx.tabbed:            # Вкладки (tabs)
      alternate_style: true
  - tables                      # Поддержка таблиц
  - toc:
      permalink: "#"            # Добавляет иконку-ссылку (#) рядом с каждым заголовком
  - attr_list # Позволяет задавать кастомные id, классы и атрибуты
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      #default_lang: bash

extra_css:
  - stylesheets/extra.css

hooks:
  - hooks/generate_pdf.py